/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/6.7/samples
 */


plugins {
    java
    eclipse
    id("io.spring.dependency-management") version "1.0.10.RELEASE"
    id("org.springframework.boot") version "2.4.1"
    //kotlin("jvm") version "1.4.21"
    //kotlin("plugin.spring") version "1.4.21"
}

repositories {
    jcenter()
}

dependencies {
    val springVersion = "2.4.1"
    //testImplementation("org.junit.jupiter", "junit-jupiter-api", "5.7.0")
    testImplementation("org.springframework.boot", "spring-boot-starter-test")
    implementation("org.springframework.boot", "spring-boot-starter-web", "2.4.1")
    implementation("org.springframework.boot", "spring-boot-gradle-plugin", "2.4.1")
}

// specify test platform : gradle(run test using)
tasks.withType<Test> {
    useJUnitPlatform()
}